# Generated by Django 3.2 on 2022-01-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220122_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
    ]
