# Generated by Django 3.2 on 2022-01-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='date_added',
        ),
    ]
