# Generated by Django 3.2 on 2022-01-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
